fix(expect): account for undefined matcherResult
Avoids the following error:
```
TypeError: Cannot read properties of undefined (reading 'suggestedRebaseline')
```