test: add repro for focus misfiring blur
Repro for #14254.
Regressed by 7a5b070e9507b622877a2af010373585f2184196.

The FF workaround introduced by
7a5b070e9507b622877a2af010373585f2184196, triggers `#focusable` to be
blurred when `#non-focusable` attempts to be focused.

This test currently fails on all three browsers:

```
  3) [firefox] › page/page-focus.spec.ts:121:4 › keeps focus on element when attempting to focus a non-focusable element

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: "focusable"
    Received: ""

      144 |   expect.soft(await page.evaluate(() => document.activeElement?.id)).toBe('focusable');
      145 |   await page.locator('#non-focusable').focus();
    > 146 |   expect.soft(await page.evaluate(() => document.activeElement?.id)).toBe('focusable');
          |                                                                      ^
      147 |   expect.soft(await page.evaluate(() => window['eventLog'])).toEqual([
      148 |     'focus focusable',
      149 |   ]);

        at //tests/page/page-focus.spec.ts:146:70

    Error: expect(received).toEqual(expected) // deep equality

    - Expected  - 0
    + Received  + 1

      Array [
        "focus focusable",
    +   "blur focusable",
      ]

      145 |   await page.locator('#non-focusable').focus();
      146 |   expect.soft(await page.evaluate(() => document.activeElement?.id)).toBe('focusable');
    > 147 |   expect.soft(await page.evaluate(() => window['eventLog'])).toEqual([
          |                                                              ^
      148 |     'focus focusable',
      149 |   ]);
      150 | });

        at //tests/page/page-focus.spec.ts:147:62
```