chore(expect): explicit errorMessage
This turns an error in the protocol in a successfull call with error
message in the new `errorMessage` field. Existing "element(s) not found"
error is migrated to this as well.

Note that expect protocol call may still throw for multiple reasons:
- server connection dropped
- failed to serialize expected/received value, e.g. in `toHaveJSProperty()`
- unexpected playwright bug

---

Strict mode violation

```
Error: expect(locator).toHaveText(expected) failed

Locator: locator('div')
Expected string: "foo"
Error: strict mode violation: locator('div') resolved to 2 elements:
    1) <div>a</div> aka getByText('a')
    2) <div>b</div> aka getByText('b')

Call log:
  - Expect "toHaveText" with timeout 5000ms
  - waiting for locator('div')
```

---

Invalid selector

```
Error: expect(locator).toBeVisible() failed

Locator:  ##
Expected: visible
Error: Unexpected token "#" while parsing css selector "##". Did you mean to CSS.escape it?

Call log:
  - Expect "toBeVisible" with timeout 5000ms
  - waiting for ##
```

---

New look for "element(s) not found" error

```
Error: expect(locator).toBeVisible() failed

Locator:  locator('span')
Expected: visible
Error: element(s) not found
Timeout:  5000ms

Call log:
  - Expect "toBeVisible" with timeout 5000ms
  - waiting for locator('span')
```