test: typo fix
Noticed this only because this test is (inexplicably) failing on my mac,
but not in GitHub Codespaces or the Mac bots.

Failure is:

```
  1) [chromium] › browsercontext-fetch.spec.ts:573:4 › should throw informatibe error on corrupted gzip body

    Error: expect(received).toContain(expected) // indexOf

    Expected substring: "failed to decompress 'gzip' encoding"
    Received string:    "apiRequestContext.get: incorrect header check
    =========================== logs ===========================
    → GET http://localhost:8907/corrupted
      user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/101.0.4921.0 Safari/537.36
      accept: */*
      accept-encoding: gzip,deflate,br
    ← 200 OK
      content-encoding: gzip
      content-type: text/plain
      date: Fri, 04 Mar 2022 21:53:18 GMT
      connection: close
      transfer-encoding: chunked
    ============================================================"
```