chore: cleanup some things
- remove roll_browser_into_playwright.yml workflow as unused;
- remove onClosePersistent() method as unused;
- fix build script to avoid copying directories (see below)

Build error:

```
Error: EISDIR: illegal operation on a directory,
copyfile '<pw>/packages/skills/component-testing' -> '<pw>/packages/playwright/lib/skills/component-testing'
```